version: "3.7"

services:
  database_hack:
    image: postgres
    container_name: database_hack
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=illuminate_db
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: app_illuminate
    ports:
      - 3333:3333
    links:
      - database_hack
    depends_on:
      - database_hack
    volumes:
      - .:/usr/app


volumes:
  pgdata:
    driver: local